version: '3'
services:
    mongodb:
        image: mongo

    server:
        build: .
        depends_on:
            - "mongodb"
        command: "npm run start:prod"
        ports: 
            - "8081:8081"
        environment:
            - NODE_ENV=production
            - PORT=9000

